### ISSUE TITLE
Add reqstool_config.yml to reqstool zip file

### ISSUE THREAD

**Issue by lfvdavid** [luftfartsverket/reqstool-java-maven-plugin#83]
Add reqstool_config.yml file to the reqstool zip file.

The reqstool_config should have this structure:

```yaml
language: java
 build: maven
 resources:
     requirements: requirements.yml
     software_verification_cases: software_verification_cases.yml
     manual_verification_results: manual_verification_results.yml
     annotations: ../../target/reqstool/annotations.yml
     test_results:
         - ../../target/failsafe
         - ../../target/surefire
```

With a minimal version that looks like this:

```yaml
    resources:
        annotations: ../../target/reqstool/annotations.yml
        test_results:
            - ../../target/failsafe
            - ../../target/surefire
```

* language: defaults to None
* build: defaults to None
* requirements: defaults to file in same directory as reqstool_config
* software_verification_cases: defaults to file in same directory as reqstool_config
* manual_verification_results: defaults to file in same directory as reqstool_config
